function run_glsl_code_gen(mod::Module, pipeline_ctx::GLSLPipelineContext, glsl_ast::GLSLASTNode)::String
    @assert glsl_ast isa GLSLShader "The GLSL AST must have a GLSLShader node as its root"

    ctx = GLSLCodeGenContext(mod)

    code = "// This code was auto-generated by the Julia -> GLSL transpiler\n\n"

    for decl in glsl_ast.interface_declarations
        code *= glsl_cg_traverse(decl, ctx) * ";\n"
    end

    if !isempty(glsl_ast.interface_declarations)
        code *= "\n"
    end

    code *= "void main() {\n"
    code *= glsl_cg_traverse(glsl_ast.body, ctx)
    code *= "}"

    code
end
