run_glsl_code_gen(mod::Module, ::GLSLPipelineContext, glsl_ast::GLSLASTNode) =
    error("The GLSL AST must have a GLSLShader or GLSLFunction node as its root")

# Method for generating the main shader function
function run_glsl_code_gen(mod::Module, pipeline_ctx::GLSLPipelineContext, glsl_ast::GLSLShader)::String
    ctx = GLSLCodeGenContext(mod)
    cfg = Transpiler.transpiler_config

    code = "#version " * string(cfg.gl_version) * (cfg.gl_core ? " core" : "") * "\n\n"
    code *= "// This code was auto-generated by the Julia -> GLSL transpiler\n\n"

    for block in glsl_ast.interface_blocks
        code *= glsl_cg_traverse(block, ctx) * ";\n"
    end

    for decl in glsl_ast.interface_declarations
        code *= glsl_cg_traverse(decl, ctx) * ";\n"
    end

    if !isempty(glsl_ast.interface_declarations)
        code *= "\n"
    end

    for (_, transpiled_helper) in pipeline_ctx.helpers
        code *= transpiled_helper * "\n"
    end

    code *= "void main() {\n"
    code *= glsl_cg_traverse(glsl_ast.body, ctx)
    code *= "}"

    code
end

# Method for generating helper shader functions (fn type info is also taken into account)
function run_glsl_code_gen(mod::Module, ::GLSLPipelineContext, glsl_ast::GLSLFunction)::String
    ctx = GLSLCodeGenContext(mod)

    code = type_to_str(glsl_ast.ret_type) * " " * glsl_cg_traverse(glsl_ast.name, ctx) * "("

    for param in glsl_ast.params
        code *= glsl_cg_traverse(param, ctx) * ", "
    end

    if !isempty(glsl_ast.params)
        code = code[1:end-2]
    end

    code *= ") {\n"
    code *= glsl_cg_traverse(glsl_ast.body, ctx)
    code *= "}\n"

    code
end
